In [2]:
import sys
import os
sys.path.append(os.path.abspath('../'))

from scipy.optimize import linprog
import numpy as np
import time
from ortc.utils import get_degree_cost, stochastic_block_model, is_connected

from ortc.entropicORTC import entropic_ortc
from ortc.entropicORTC_edge import entropic_ortc_edge
from ortc.glop_v2 import glop_v2

In [24]:
np.random.seed(10)

In [25]:
m1 = 4
m2 = 4
A1 = stochastic_block_model(np.array([m1,m1,m1,m1]), np.array([[1,0.1,0.1,0.1],[0.1,0.9,0.1,0.1],[0.1,0.1,0.8,0.1],[0.1,0.1,0.1,0.7]]))
A2 = stochastic_block_model(np.array([m2,m2,m2,m2]), np.array([[1,0.1,0.1,0.1],[0.1,0.9,0.1,0.1],[0.1,0.1,0.8,0.1],[0.1,0.1,0.1,0.7]]))
A1 = A1 / np.sum(A1)
A2 = A2 / np.sum(A2)
c = get_degree_cost(A1, A2)

In [26]:
start = time.time()
a, exp_cost, weight = glop_v2(A1, A2, c)
end = time.time()
print(exp_cost)
print(end - start)

0.0002387450464868163
1.1974880695343018


In [27]:
start = time.time()
w, exp_cost, n, iter_his1, cost_his1 = entropic_ortc(A1, A2, c, 0.0002, 100000, 1e-8)
end = time.time()
print(exp_cost)
print(end - start)

0.00026963333345112405
28.89102602005005


In [28]:
print(iter_his1[-1])

22033


In [29]:
print(cost_his1)

[0.00012539244213243664, 0.00014472286295282973, 0.0001602513725873588, 0.00017231232490590674, 0.00018188372645939913, 0.00018967962583260825, 0.00019615463224169965, 0.00020160629338338213, 0.00020624100259367071, 0.00021020951369934423, 0.0002136265840341307, 0.00021658240927125864, 0.00021914958941026785, 0.0002213875689599968, 0.00022334560598868576, 0.00022506485567508282, 0.00022657989986192667, 0.00022791991425038437, 0.00022910958676526424, 0.0002301698564892804, 0.00023111851739980694, 0.00023197071661116872, 0.00023273936823017257, 0.00023343549862455792, 0.0002340685354143397, 0.00023464655002968434, 0.00023517646181820718, 0.00023566421021507805, 0.00023611490030102868, 0.00023653292610597982, 0.00023692207523085673, 0.00023728561772707192, 0.0002376263816654347, 0.00023794681741970468, 0.00023824905236321874, 0.00023853493741205682, 0.0002388060866307065, 0.0002390639109352647, 0.00023930964677686828, 0.0002395443805585423, 0.00023976906942788204, 0.00023998455899294807, 

In [30]:
start = time.time()
w, exp_cost, n, iter_his2, cost_his2 = entropic_ortc_edge(A1, A2, c, 0.0002, 10000, 1e-8)
end = time.time()
print(exp_cost)
print(end - start)

[[1.1506593  1.1506593  1.1506593  ... 1.20181614 1.1506593  1.1506593 ]
 [0.86906698 0.86906698 0.86906698 ... 1.10258926 0.86906698 0.86906698]
 [1.1506593  1.1506593  1.1506593  ... 1.20181614 1.1506593  1.1506593 ]
 ...
 [1.34955    1.34955    1.34955    ... 1.55550215 1.34955    1.34955   ]
 [3.07394178 3.07394178 3.07394178 ... 4.98343918 3.07394178 3.07394178]
 [0.3253152  0.3253152  0.3253152  ... 0.44084843 0.3253152  0.3253152 ]]
[[ 1.37051644  1.37051644  1.37051644 ...  1.4278864   1.34775515
   1.34775515]
 [ 0.72965195  0.72965195  0.72965195 ...  1.13192064  0.74197453
   0.74197453]
 [ 1.40063612  1.40063612  1.40063612 ...  1.46090087  1.35087937
   1.35087937]
 ...
 [ 2.06417532  2.06417532  2.06417532 ...  2.81958648  1.9186225
   1.9186225 ]
 [ 5.50310478  5.50310478  5.50310478 ... 12.90403283  5.32619291
   5.32619291]
 [ 0.1817156   0.1817156   0.1817156  ...  0.31125763  0.18775137
   0.18775137]]
[[ 1.5845788   1.5845788   1.5845788  ...  1.70041141  1.5289106


In [31]:
print(iter_his2[-1])

1367


In [32]:
print(cost_his2)

[0.00012539244213243664, 0.0001460297516397566, 0.0001635773981111528, 0.00017702946442109895, 0.00018712823519248436, 0.00019493044163910084, 0.00020119386063225644, 0.00020637341544438423, 0.000210736829503191, 0.0002144515853487828, 0.0002176328086167578, 0.00022036706526001033, 0.00022272379374779097, 0.00022476080994806387, 0.00022652711004599572, 0.00022806449659239003, 0.00022940869966463353, 0.00023059026113414244, 0.0002316352711754795, 0.00023256597848364877, 0.00023340128548102185, 0.00023415715312682117, 0.0002348469486891767, 0.00023548176219404746, 0.0002360707011960024, 0.00023662116164137472, 0.00023713906926697617, 0.00023762908838989965, 0.00023809479919706622, 0.00023853884847903047, 0.00023896308129249132, 0.00023936866204019226, 0.0002397561929762456, 0.00024012583634198647, 0.0002404774432266352, 0.0002408106875285467, 0.00024112519697223794, 0.00024142066659057576, 0.00024169693765327367, 0.00024195403134997365, 0.00024219214117978267, 0.00024241160298647775, 0.0

In [6]:
m1 = 200
A1 = stochastic_block_model(np.array([m1]), np.array([[2/3]]))
A2 = A1.copy()

#permute nodes
A2[[0, 2], :] = A2[[2, 0], :]     # swap row 0 with row 2
A2[[1, 5], :] = A2[[5, 1], :]
A2[[9, 20], :] = A2[[20, 9], :]
A2[:, [0, 2]] = A2[:, [2, 0]]     # swap column 0 with column 2
A2[:, [1, 5]] = A2[:, [5, 1]]
A2[:, [9, 20]] = A2[:, [20, 9]]

A1 = A1 / np.sum(A1)
A2 = A2 / np.sum(A2)

c = get_degree_cost(A1,A2)

d1 = np.sum(A1, axis=1)
d2 = np.sum(A2, axis=1)

print(is_connected(A1))
print(is_connected(A2))

epsi = 0.1
niter = 10
delta = 1e-10

start = time.time()
w_1, exp_cost_1, n_1, iter_his_1, cost_his_1 = entropic_ortc_edge(A1, A2, c, epsi, niter, delta)
end = time.time()
print(end - start)

True
True
[[1.00000017 0.99999851 1.         ... 0.99999944 0.99999938 0.99999923]
 [1.00000149 0.99999983 1.00000122 ... 1.00000052 1.00000077 1.00000062]
 [1.00000084 0.99999916 1.00000065 ... 0.99999991 0.99999989 0.99999996]
 ...
 [1.00000072 0.99999917 1.00000052 ... 1.00000003 1.00000001 0.99999994]
 [1.00000098 0.99999926 1.00000077 ... 1.00000001 1.00000004 1.        ]
 [1.00000074 0.99999902 1.00000062 ... 0.99999994 1.         0.99999996]]
2576.9195206165314


In [7]:
iter_his_1[-1]

2

In [8]:
cost_his_1

[1.4803693982153615e-07]

In [9]:
iter_his_1

[1, 2]

In [10]:
start = time.time()
w_1, exp_cost_1, n_1, iter_his_1, cost_his_1 = entropic_ortc(A1, A2, c, epsi, niter, delta)
end = time.time()
print(end - start)

4463.830733060837
